import os
from dotenv import load_dotenv

load_dotenv()


class LLMClient:
    """
    LLM abstraction layer.

    Supports:
    - mock: local placeholder response
    - gemini: Google Gemini API via google-genai SDK

    The rest of the application should only call:
        LLMClient.generate(prompt)
    """

    def __init__(self):
        self.provider = os.getenv("LLM_PROVIDER", "mock").lower()
        self.model = os.getenv("GEMINI_MODEL", "gemini-3-flash-preview")

        self.gemini_client = None

        if self.provider == "gemini":
            self._init_gemini()

    def _init_gemini(self):
        api_key = os.getenv("GEMINI_API_KEY")

        if not api_key:
            print("GEMINI_API_KEY not found. Falling back to mock LLM.")
            self.provider = "mock"
            return

        try:
            from google import genai

            self.gemini_client = genai.Client(api_key=api_key)
            print(f"Gemini LLM initialized with model: {self.model}")

        except Exception as e:
            print(f"Failed to initialize Gemini client: {e}")
            print("Falling back to mock LLM.")
            self.provider = "mock"

    def generate(self, prompt: str) -> str:
        if self.provider == "gemini":
            return self._generate_with_gemini(prompt)

        return self._generate_mock(prompt)

    def _generate_with_gemini(self, prompt: str) -> str:
        try:
            response = self.gemini_client.models.generate_content(
                model=self.model,
                contents=prompt,
            )

            if response and response.text:
                return response.text

            return "No response generated by Gemini."

        except Exception as e:
            return f"Gemini API error: {str(e)}"

    def _generate_mock(self, prompt: str) -> str:
        question = self._extract_question(prompt)
        question_lower = question.lower()

        if "cloud connect" in question_lower:
            return "Cloud Connect is a managed connectivity solution that enables seamless connectivity."

        if "polarin" in question_lower or "naas" in question_lower:
            return "Polarin NaaS is a network-as-a-service offering that helps manage network services efficiently."

        if "traffic" in question_lower:
            return "Traffic refers to the flow of data across the network."

        if "packet" in question_lower or "packets" in question_lower:
            return "Packets are discrete units of data transmitted across a network."

        if "latency" in question_lower:
            return "Latency is the time delay in network communication."

        return "I found relevant context, but the mock LLM does not yet support a specific answer for this question."

    def _extract_question(self, prompt: str) -> str:
        if "Question:" not in prompt:
            return prompt

        question_part = prompt.split("Question:", 1)[1]

        if "Answer" in question_part:
            question_part = question_part.split("Answer", 1)[0]

        return question_part.strip()